export const ABRIR_CERRAR_MODAL = 'ABRIR_CERRAR_MODAL';

export const AGREGAR_REGISTRO = 'AGREGAR_REGISTRO';
export const AGREGAR_REGISTRO_EXITO = 'AGREGAR_REGISTRO_EXITO';
export const AGREGAR_REGISTRO_ERROR = 'AGREGAR_REGISTRO_ERROR';

export const COMENZAR_DESCARGA_REGISTROS= 'COMENZAR_DESCARGA_REGISTROS';
export const DESCARGA_REGISTRO_EXITO= 'DESCARGA_REGISTRO_EXITO';
export const DESCARGA_REGISTRO_ERROR= 'DESCARGA_REGISTRO_ERROR';


export const COMENZAR_DESCARGA_FAVORITOS= 'COMENZAR_DESCARGA_FAVORITOS';
export const DESCARGA_FAVORITOS_EXITO= 'DESCARGA_FAVORITOS_EXITO';
export const DESCARGA_FAVORITOS_ERROR= 'DESCARGA_FAVORITOS_ERROR';

export const AGREGAR_FAVORITO = 'AGREGAR_FAVORITO';